---
- name: Download Flannel pod network add-on
  become_user: "{{ admin_user }}"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yml
    mode: 0664

- name: Install Flannel pod network add-on
  become_user: "{{ admin_user }}"
  kubernetes.core.k8s:
    state: present
    src: /tmp/kube-flannel.yml