---
- name: Install supporting packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - python3
      - python3-jsonpatch
      - python3-kubernetes
      - python3-yaml
      - rsync
    state: present
    update_cache: true
  tags:
    - installation
    - packages

- name: Check swap
  shell: free -m | grep -i swap | awk '{print $2}'
  register: swap_size
  changed_when: false

- name: Load kernel modules on boot
  ansible.builtin.copy:
    dest: "/etc/modules-load.d/k8s.conf"
    content: |
      overlay
      br_netfilter

- name: Modprobe overlay
  community.general.modprobe:
    name: overlay
    state: present

- name: Modprobe br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Configure netfilter
  ansible.builtin.copy:
    dest: "/etc/sysctl.d/99-k8s.conf"
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Set Netfilter IPv4
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Set Netfilter IPv6
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Set IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Install Containerd
  ansible.builtin.apt:
    name: containerd
    state: present

# Debian's containerd version 1.4 is too low and runs into problems
# Version 1.6 is needed, manually override to 1.6
- name: Get Containerd version
  ansible.builtin.shell: containerd -v | awk '{print $3}'
  register: containerd_version
  changed_when: false

- name: Containerd version
  ansible.builtin.debug:
    msg: "{{ containerd_version.stdout }}"

- name: Containerd 1.4 bugfix
  block:
    - name: Stop Containerd
      ansible.builtin.systemd:
        name: containerd
        state: stopped

    - name: Download Containerd 1.6.20
      ansible.builtin.get_url:
        url: https://github.com/containerd/containerd/releases/download/v1.6.20/containerd-1.6.20-linux-amd64.tar.gz
        dest: /tmp/containerd-1.6.20-linux-amd64.tar.gz

    - name: Extract binaries into /usr/bin
      ansible.builtin.unarchive:
        src: /tmp/containerd-1.6.20-linux-amd64.tar.gz
        dest: /usr
        remote_src: yes

    - name: Start Containerd
      ansible.builtin.systemd:
        name: containerd
        state: started
  when: containerd_version.stdout != containerd_version_pinned

- name: Copy default containerd config
  ansible.builtin.template:
    src: config.toml
    dest: /etc/containerd/config.toml
  notify:
    - Restart containerd
  tags:
    - configuration

- name: Add Google Cloud public signing key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
    mode: "0644"
    force: true

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    filename: /etc/apt/sources.list.d/kubernetes.list
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubectl
      - kubelet
    state: present
    update_cache: true

- name: Hold kubeadm
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubectl
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold

- name: Hold kubelet
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold
