---
- import_playbook: ipv4-forwarding.yml
- import_playbook: python.yml
- import_playbook: containerd.yml
- import_playbook: kubes.yml
- import_playbook: master.yml
- import_playbook: flannel.yml
- import_playbook: worker.yml
- import_playbook: metallb.yml
